[package]

name = "2DPG"
version = "0.0.1"
authors = ["Lolirofle <lolipopple@hotmail.com>"]

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[[bin]]
name = "2DPG"
