[package]

name = "2dgl"
version = "0.0.2"
authors = ["Lolirofle <lolipopple@hotmail.com>"]

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dependencies.num]
git = "https://github.com/rust-lang/num"
